# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '50 15 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        #
    - name: Update zhihu
      run: |
        cd zhihu
        sh run.sh

    - name: Update lanpang on bilibili
      run: |
        cd bilibili/lanpang
        sh run.sh

    - name: Update guodong on bilibili
      run: |
        cd bilibili/guodong
        sh run.sh

    - name: Commit
      run: |
        git config --global user.email guodongxiaren@163.com
        git config --global user.name guodongxiaren
        git add .
        #git commit -m"action:`date +'%Y-%m-%d'`"
        git commit -m"action:`date`"
        git pull --rebase

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
